# Generated by Django
from django.db import migrations

def add_images_to_products(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    
    # Качественные и стабильные URL картинок из интернета (Unsplash / Pixabay)
    images_pool = {
        'spinning': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800&auto=format&fit=crop', # Удочки / Спиннинги
        'reel': 'https://images.unsplash.com/photo-1611091531065-ef7e4360a89d?q=80&w=800&auto=format&fit=crop',     # Катушки
        'bait': 'https://cdn.pixabay.com/photo/2016/11/29/03/15/bait-1867011_1280.jpg',                             # Прикормки / Наживки
        'lure': 'https://images.unsplash.com/photo-1516246838873-9d3265952d1b?q=80&w=800&auto=format&fit=crop',     # Блесны / Воблеры / Крючки
        'boat': 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=800&auto=format&fit=crop',     # Лодки / Снаряжение
        'default': 'https://images.unsplash.com/photo-1517462964-21fdcec3f25b?q=80&w=800&auto=format&fit=crop'       # Универсальная (Рыбалка)
    }

    for product in Product.objects.all():
        name_lower = product.name.lower()
        definition_lower = (product.definition or "").lower()
        
        # Логика подбора картинки по ключевым словам в названии или описании товара
        if any(w in name_lower or w in definition_lower for w in ['удоч', 'спиннинг', 'удилище', 'фидер']):
            product.photo = images_pool['spinning']
        elif any(w in name_lower or w in definition_lower for w in ['катушк', 'reel']):
            product.photo = images_pool['reel']
        elif any(w in name_lower or w in definition_lower for w in ['прикорм', 'бойл', 'наживка', 'живц']):
            product.photo = images_pool['bait']
        elif any(w in name_lower or w in definition_lower for w in ['блесн', 'воблер', 'крючок', 'леска', 'поплавок', 'приманк']):
            product.photo = images_pool['lure']
        elif any(w in name_lower or w in definition_lower for w in ['лодк', 'эхолот', 'палатк', 'костюм', 'сапог']):
            product.photo = images_pool['boat']
        else:
            product.photo = images_pool['default']
            
        product.save()

def reverse_images(apps, schema_editor):
    # На случай, если захочется откатить миграцию назад
    Product = apps.get_model('shop', 'Product')
    for product in Product.objects.all():
        product.photo = ""
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        # ВАЖНО: Здесь автоматически должна быть указана ваша ПРЕДЫДУЩАЯ миграция.
        # Например, если файл называется 0002_..., то тут будет ('shop', '0001_initial')
        # Оставьте ту строку, которую Django сгенерировал изначально в блоке dependencies!
    ('shop', '0003_profile'),
    ]

    operations = [
        migrations.RunPython(add_images_to_products, reverse_code=reverse_images),
    ]